# Site
locale: en-US
site_theme: default
title: Moran Li
name: Moran Li
title_separator: "-"
description: "Research homepage of Moran Li"
url: https://moranli-aca.github.io
repository: moranli-aca/moranli-aca.github.io
timezone: Etc/UTC
future: true

# Profile
author:
  avatar: profile.jpg
  name: Moran Li
  bio: Researcher, TikTok
  location: Shanghai
  email: moranli.aca@gmail.com
  github: moranli-aca
  googlescholar: https://scholar.google.com/citations?user=8pvT01UAAAAJ
  orcid: https://orcid.org/0000-0002-8149-1117

# Content
include:
  - _pages
exclude:
  - .bundle
  - .github
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

collections:
  publications:
    output: true
    permalink: /publication/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true

# Rendering
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
img_path: /images/paper/
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo
sass:
  sass_dir: _sass
  style: compressed

# GitHub Pages
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
whitelist:
  - jekyll-sitemap
  - jekyll-redirect-from
